name: PREVIEWSpyglassDockerBuild

on:
  # Run this workflow automatically if IntegrationAPITests completed successfully
  workflow_run:
    workflows: [IntegrationAPITests]
    types: 
      - completed
  # Allows manual run of this workflow from the Actions tab (on any branch)
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:
  build:
    # Run this workflow automatically only on develop (see last line of the 'if' statement)
    if: >
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.head_branch == 'develop')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Build the Docker image
      run: docker build --no-cache -t swirlai/spyglass:preview  -f Dockerfile.develop.spg .
    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push swirlai/spyglass:preview
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
